name: network_proxy
description: Network proxy
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  crypto: ^3.0.3
  cupertino_icons: ^1.0.2
  basic_utils: ^5.7.0
  logger: ^2.0.1
  date_format: ^2.0.7
  window_manager: ^0.3.8
  desktop_multi_window:
    git:
      url: https://gitee.com/wanghongenpin/flutter-plugins.git
      path: packages/desktop_multi_window
  path_provider: ^2.1.2
  url_launcher: ^6.2.4
  proxy_manager: ^0.0.3
  qr_flutter: ^4.1.0
  easy_permission: ^1.0.0
  qrscan: ^0.3.3
  flutter_barcode_scanner: ^2.0.0
  flutter_toastr: ^1.0.3
  share_plus: ^8.0.2
  brotli: ^0.6.0
  file_selector: ^1.0.2
  flutter_js: ^0.8.0
  flutter_code_editor:
  file_picker: ^8.0.0
  flutter_desktop_context_menu: ^0.2.0
  win32audio: ^1.3.1
  http: ^1.2.1
  provider: ^6.1.2
  

  image_picker: ^1.1.0
#  google_places_picker: ^3.0.2

  crypton: ^2.2.1
  sizer: ^2.0.15

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  bubble_bottom_bar: ^2.0.0
  web_socket_channel: ^2.3.0
  
#  video_player:
#    git:
#      url: https://github.com/icapps/plugins.git
#      ref: feature/ios-pip
#      path: packages/video_player/video_player


#dependency_overrides:
#  video_player_platform_interface:
#    git:
#      url: https://github.com/icapps/plugins.git
#      ref: feature/ios-pip
#      path: packages/video_player/video_player_platform_interface
#  video_player_avfoundation:
#    git:
#      url: https://github.com/icapps/plugins.git
#      ref: feature/ios-pip
#      path: packages/video_player/video_player_avfoundation
#  video_player_android:
#    git:
#      url: https://github.com/icapps/plugins.git
#      ref: feature/ios-pip
#      path: packages/video_player/video_player_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/certs/ca.crt
    - assets/certs/ca_private.der
    - assets/icon.png
    - assets/images/camera/
    - assets/images/chat/
    - assets/images/feed/
    - assets/images/media/
    - assets/images/navigation/
    - assets/images/profile/
    - assets/images/shopping/
    - assets/images/signup/
    - assets/images/statistics/
    - assets/images/walkthrough/
    - assets/images/main/